-- MySQL Script generated by MySQL Workbench
-- Fri Sep 16 12:55:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema mini_ec
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mini_ec` ;

-- -----------------------------------------------------
-- Schema mini_ec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mini_ec` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `mini_ec` ;

-- -----------------------------------------------------
-- Table `carrinho_compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrinho_compras` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `carrinho_compras` (
  `sessao` VARCHAR(32) NOT NULL,
  `id_produto` INT NOT NULL,
  `qtd` INT NOT NULL,
  `val_unit` DECIMAL(10,2) NOT NULL,
  `desconto` DECIMAL(10,2) NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `data_hora_sessa` DATETIME NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `ix_cc_1` ON `carrinho_compras` (`sessao` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categorias` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cidades` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cidades` (
  `id_cidade` INT NOT NULL AUTO_INCREMENT,
  `nome_cidade` VARCHAR(70) NOT NULL,
  `cod_mun` CHAR(7) NOT NULL,
  `cod_uf` TINYINT NOT NULL,
  PRIMARY KEY (`id_cidade`))
ENGINE = InnoDB
AUTO_INCREMENT = 5571
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cliente_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente_endereco` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cliente_endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `tipo` ENUM('P', 'A') NOT NULL,
  `endereco` VARCHAR(60) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(30) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `id_cidade` INT NOT NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(32) NOT NULL,
  `sobrenome` VARCHAR(32) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `data_cadastro` DATETIME NOT NULL,
  `ult_acesso` DATETIME NULL DEFAULT NULL,
  `ult_compra` DATETIME NULL DEFAULT NULL,
  `situacao` ENUM('A', 'B') NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cond_pagto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cond_pagto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cond_pagto` (
  `id_pagto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NOT NULL,
  `tipo` ENUM('C', 'D', 'B') NOT NULL,
  PRIMARY KEY (`id_pagto`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cond_pagto_det`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cond_pagto_det` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cond_pagto_det` (
  `id_pagto` INT NOT NULL,
  `parcela` INT NOT NULL,
  `percentual` DECIMAL(10,2) NULL DEFAULT NULL,
  `dias` INT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estoque` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `estoque` (
  `id_produto` INT NOT NULL,
  `estoque_total` INT NOT NULL,
  `estoque_livre` INT NULL DEFAULT NULL,
  `estoque_reservado` INT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fabricantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fabricantes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fabricantes` (
  `id_fabricante` INT NOT NULL AUTO_INCREMENT,
  `nome_fabricante` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_fabricante`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nf_itens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nf_itens` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `nf_itens` (
  `num_nota` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `qtd` INT NOT NULL,
  `val_unit` DECIMAL(10,2) NOT NULL,
  `desconto` DECIMAL(10,2) NOT NULL,
  `total` DECIMAL(10,2) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nf_obs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nf_obs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `nf_obs` (
  `num_nota` INT NOT NULL,
  `obs` VARCHAR(255) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nota_fiscal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nota_fiscal` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `nota_fiscal` (
  `num_nota` INT NOT NULL AUTO_INCREMENT,
  `num_ped_ref` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_endereco` INT NOT NULL,
  `id_pagto` INT NOT NULL,
  `total_prod` DECIMAL(10,2) NULL DEFAULT NULL,
  `total_frete` DECIMAL(10,2) NULL DEFAULT NULL,
  `total_desc` DECIMAL(10,2) NULL DEFAULT NULL,
  `total_nf` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_nf` DATETIME NOT NULL,
  `status_nf` ENUM('N', 'C', 'D') NULL DEFAULT NULL,
  `id_user` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`num_nota`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pedido_itens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedido_itens` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pedido_itens` (
  `num_pedido` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `qtd` INT NOT NULL,
  `val_unit` DECIMAL(10,2) NULL DEFAULT NULL,
  `desconto` DECIMAL(10,2) NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pedido_obs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedido_obs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pedido_obs` (
  `num_pedido` INT NOT NULL,
  `obs` VARCHAR(255) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedidos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pedidos` (
  `num_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_endereco` INT NOT NULL,
  `id_pagto` INT NOT NULL,
  `total_prod` DECIMAL(10,2) NULL DEFAULT NULL,
  `total_frete` DECIMAL(10,2) NULL DEFAULT NULL,
  `total_desc` DECIMAL(10,2) NULL DEFAULT NULL,
  `total_pedido` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_pedido` DATETIME NOT NULL,
  `previsao_entrega` DATE NULL DEFAULT NULL,
  `efetiva_entrega` DATE NULL DEFAULT NULL,
  `status_ped` ENUM('A', 'S', 'F', 'T', 'E') NULL DEFAULT NULL,
  PRIMARY KEY (`num_pedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `id_categoria` INT NOT NULL,
  `id_fabricante` INT NOT NULL,
  `preco_custo` DECIMAL(10,2) NULL DEFAULT NULL,
  `preco_venda` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `produto_caracter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `produto_caracter` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `produto_caracter` (
  `id_produto` INT NOT NULL,
  `caracteristica` VARCHAR(50) NOT NULL,
  `valor` VARCHAR(50) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rastreabilidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rastreabilidade` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rastreabilidade` (
  `num_pedido` INT NOT NULL,
  `status_ped` CHAR(1) NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `id_user` VARCHAR(50) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `unidade_federal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unidade_federal` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `unidade_federal` (
  `cod_uf` TINYINT NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `nome_uf` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cod_uf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nome_user` VARCHAR(50) NOT NULL,
  `email_user` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `data_cadastro` DATETIME NOT NULL,
  `status` ENUM('A', 'B') NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ix_usr_1` ON `usuarios` (`email_user` ASC) VISIBLE;

SHOW WARNINGS;
USE `mini_ec` ;

-- -----------------------------------------------------
-- View `v_financeiro`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `v_financeiro` ;
SHOW WARNINGS;
USE `mini_ec`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `v_financeiro` AS select `a`.`num_nota` AS `num_nota`,`a`.`id_cliente` AS `id_cliente`,`d`.`nome` AS `nome`,`a`.`id_pagto` AS `id_pagto`,`b`.`descricao` AS `descricao`,`b`.`tipo` AS `tipo`,`a`.`total_nf` AS `total_nf`,`a`.`data_nf` AS `data_nf`,`c`.`parcela` AS `parcela`,`c`.`percentual` AS `percentual`,`c`.`dias` AS `dias`,cast(((`a`.`total_nf` / 100) * `c`.`percentual`) as decimal(10,2)) AS `valor_parcela`,cast((`a`.`data_nf` + interval `c`.`dias` day) as date) AS `vencimento` from (((`nota_fiscal` `a` join `cond_pagto` `b` on((`a`.`id_pagto` = `b`.`id_pagto`))) join `cond_pagto_det` `c` on(((`a`.`id_pagto` = `b`.`id_pagto`) and (`a`.`id_pagto` = `c`.`id_pagto`)))) join `clientes` `d` on((`a`.`id_cliente` = `d`.`id_cliente`))) where (`a`.`status_nf` = 'N');
SHOW WARNINGS;
USE `mini_ec`;

DELIMITER $$

USE `mini_ec`$$
DROP TRIGGER IF EXISTS `Tgr_insert_status_ped` $$
SHOW WARNINGS$$
USE `mini_ec`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `mini_ec`.`Tgr_insert_status_ped`
AFTER INSERT ON `mini_ec`.`pedidos`
FOR EACH ROW
begin
 insert into rastreabilidade values(new.num_pedido,new.status_ped,now(),user());
 end$$

SHOW WARNINGS$$

USE `mini_ec`$$
DROP TRIGGER IF EXISTS `Tgr_update_status_ped` $$
SHOW WARNINGS$$
USE `mini_ec`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `mini_ec`.`Tgr_update_status_ped`
AFTER UPDATE ON `mini_ec`.`pedidos`
FOR EACH ROW
begin
 insert into rastreabilidade values(new.num_pedido,new.status_ped,now(),user());
 end$$

SHOW WARNINGS$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
